name: Deploy training/gatsby-starter-hello-world

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git config user.email "lukasz.createam@gmail.com"
      - run: git config user.name "kilmajster"
      - run: yarn --cwd training/gatsby-starter-hello-world install
      - run: yarn --cwd training/gatsby-starter-hello-world deploy
