name: Deploy training/gatsby-starter-hello-world to GH pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install training/gatsby-starter-hello-world
        run: yarn --cwd training/gatsby-starter-hello-world install
      - name: Build training/gatsby-starter-hello-world
        run: yarn --cwd training/gatsby-starter-hello-world build
      - name: Deploy training/gatsby-starter-hello-world
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./training/gatsby-starter-hello-wordl/public