name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn --cwd training/gatsby-starter-hello-world build
      - uses: JamesIves/github-pages-deploy-action@v4
        working-directory: training/gatsby-starter-hello-world
        with:
          folder: public
