name: main

on:
  push:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install:all
      - run: yarn build:all
      - run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "ci-bot"
          yarn deploy:all
